alias: "Telegram Home Callback"

trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    data: '/start'

action:
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: "
    *Home Status* {{ states.input_select.adobe_status.state }}
    
    *Light Theme* {{ states.input_select.current_light_theme.state }}
    
    
    {{'\U0001F3E0'}} *List of Command*
    "
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
    inline_keyboard:
      - "{{'\U000026A1'}} Switch:/switch, {{'\U0001F4A1'}}Light:/light, {{'\U000025B6'}} Media:/media, {{'\U0001F464'}} Family:/family"
      - "{{'\U0001F4E5'}} Service:/service, {{'\U00002699'}} System:/system, {{'\U0000274E'}} Close:/remove_button"