- alias: "Telegram Family Menu"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/family'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: "{{'\U0001F464'}} *List of Family*"
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - "Joko:/joko"
        - "{{'\U0001F3E0'}} Home Menu:/start"

################################################################################

- alias: "Telegram Joko Location"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/joko'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: "{{ trigger.event.data.message.message_id }}"
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      title: "{{'\U0001F464'}} *Joko Location* {{ states.sensor.joko_to_home.attributes.distance }} to home, {{ states.sensor.joko_to_home.attributes.duration_in_traffic }} driving"
      message:  "Address: {{ states.sensor.joko_to_home.attributes.origin_addresses }}"
  - service: telegram_bot.send_location
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      latitude: '{{ states.device_tracker.google_maps_101676721020210595319.attributes.latitude }}'
      longitude: '{{ states.device_tracker.google_maps_101676721020210595319.attributes.longitude }}'
  - service: telegram_bot.send_message
    data_template:
      message: "{{'\U0001F464'}} *List of Family*"
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - "Joko:/joko"
        - "{{'\U0001F3E0'}} Home Menu:/start"

################################################################################

