- alias: "Telegram Light Menu"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/light'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '*List of Light*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - 'Main Light:/light_main'
        - 'Home Menu:/start'

################################################################################
