- alias: "Telegram Media Menu"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/media'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: "{% if is_state('media_player.volumio', 'playing') %}▶️ *Volumio* is {{ states('media_player.volumio') }}
{% elif is_state('media_player.volumio', 'paused') %}▶️ *Volumio* is {{ states('media_player.volumio') }}
{% elif is_state('media_player.volumio', 'idle') %}▶️ *Volumio* is {{ states('media_player.volumio') }}
{% else %}{% endif %}
{% if is_state('media_player.mpc', 'playing') %}▶️ *MPC* is {{ states('media_player.mpc') }}
{% elif is_state('media_player.mpc', 'paused') %}▶️ *MPC* is {{ states('media_player.mpc') }}
{% elif is_state('media_player.mpc', 'idle') %}▶️ *MPC* is {{ states('media_player.mpc') }}
{% else %}{% endif %}
{% if is_state('media_player.kodi', 'playing') %}▶️ *Kodi* is {{ states('media_player.kodi') }}
{% elif is_state('media_player.kodi', 'paused') %}▶️ *Kodi* is {{ states('media_player.kodi') }}
{% elif is_state('media_player.kodi', 'idle') %}▶️ *Kodi* is {{ states('media_player.kodi') }}
{% else %}{% endif %}
{% if is_state('media_player.chrome', 'playing') %}▶️ *Chrome* is {{ states('media_player.chrome') }}
{% elif is_state('media_player.chrome', 'paused') %}▶️ *Chrome* is {{ states('media_player.chrome') }}
{% elif is_state('media_player.chrome', 'idle') %}▶️ *Chrome* is {{ states('media_player.chrome') }}
{% else %}{% endif %}


▶️ *List of Media*"
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - "Volumio:/volumio{% if is_state('media_player.mpc', 'playing') %}, MPC:/mpc{% elif is_state('media_player.mpc', 'paused') %}, MPC:/mpc{% else %}{% endif %}{% if is_state('media_player.kodi', 'playing') %}, Kodi:/kodi{% elif is_state('media_player.kodi', 'paused') %}, Kodi:/kodi{% else %}{% endif %}{% if is_state('media_player.chrome', 'playing') %}, Plex Chrome:/chrome{% elif is_state('media_player.chrome', 'paused') %}, Plex Chrome:/chrome{% else %}{% endif %}"
        - 'Home Menu:/start'
################################################################################
