- alias: "Telegram Chrome"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/chrome'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '▶️ *Chrome* {{ states.media_player.chrome.state }} *{{ states.media_player.chrome.attributes.media_artist }}* - *{{ states.media_player.chrome.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/chrome_prev, ⏯️ Play/Pause:/chrome_playpause, ⏭️ Next:/chrome_next'
        - 'Reload:/chrome, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Chrome Prev"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/chrome_prev'
  action:
  - service: media_player.media_previous_track
    entity_id: media_player.chrome
  - delay: 00:00:07
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '▶️ *Chrome* {{ states.media_player.chrome.state }} *{{ states.media_player.chrome.attributes.media_artist }}* - *{{ states.media_player.chrome.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/chrome_prev, ⏯️ Play/Pause:/chrome_playpause, ⏭️ Next:/chrome_next'
        - 'Reload:/chrome, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Chrome Play"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/chrome_playpause'
  action:
  - service: media_player.media_play_pause
    entity_id: media_player.chrome
  - delay: 00:00:07
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '▶️ *Chrome* {{ states.media_player.chrome.state }} *{{ states.media_player.chrome.attributes.media_artist }}* - *{{ states.media_player.chrome.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/chrome_prev, ⏯️ Play/Pause:/chrome_playpause, ⏭️ Next:/chrome_next'
        - 'Reload:/chrome, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Chrome Next"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/chrome_next'
  action:
  - service: media_player.media_next_track
    entity_id: media_player.chrome
  - delay: 00:00:07
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '▶️ *Chrome* {{ states.media_player.chrome.state }} *{{ states.media_player.chrome.attributes.media_artist }}* - *{{ states.media_player.chrome.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/chrome_prev, ⏯️ Play/Pause:/chrome_playpause, ⏭️ Next:/chrome_next'
        - 'Reload:/chrome, Home Menu:/start, ↩️ Back:/media'

################################################################################
