- alias: "Telegram Kodi"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/kodi'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.kodi.attributes.entity_picture }}
      caption: '▶️ *Kodi* {{ states.media_player.kodi.state }} *{{ states.media_player.kodi.attributes.media_artist }}* - *{{ states.media_player.kodi.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/kodi_prev, ⏯️ Play/Pause:/kodi_playpause, ⏭️ Next:/kodi_next'
        - 'Reload:/kodi, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Kodi Prev"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/kodi_prev'
  action:
  - service: media_player.media_previous_track
    entity_id: media_player.kodi
  - delay: 00:00:01
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.kodi.attributes.entity_picture }}
      caption: '▶️ *Kodi* {{ states.media_player.kodi.state }} *{{ states.media_player.kodi.attributes.media_artist }}* - *{{ states.media_player.kodi.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/kodi_prev, ⏯️ Play/Pause:/kodi_playpause, ⏭️ Next:/kodi_next'
        - 'Reload:/kodi, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Kodi Play"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/kodi_playpause'
  action:
  - service: media_player.media_play_pause
    entity_id: media_player.kodi
  - delay: 00:00:01
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.kodi.attributes.entity_picture }}
      caption: '▶️ *Kodi* {{ states.media_player.kodi.state }} *{{ states.media_player.kodi.attributes.media_artist }}* - *{{ states.media_player.kodi.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/kodi_prev, ⏯️ Play/Pause:/kodi_playpause, ⏭️ Next:/kodi_next'
        - 'Reload:/kodi, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Kodi Next"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/kodi_next'
  action:
  - service: media_player.media_next_track
    entity_id: media_player.kodi
  - delay: 00:00:01
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.kodi.attributes.entity_picture }}
      caption: '▶️ *Kodi* {{ states.media_player.kodi.state }} *{{ states.media_player.kodi.attributes.media_artist }}* - *{{ states.media_player.kodi.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/kodi_prev, ⏯️ Play/Pause:/kodi_playpause, ⏭️ Next:/kodi_next'
        - 'Reload:/kodi, Home Menu:/start, ↩️ Back:/media'

################################################################################
