- alias: "Telegram MPC"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/mpc'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '▶️ *MPC* {{ states.media_player.mpc.state }} *{{ states.media_player.mpc.attributes.media_artist }}* - *{{ states.media_player.mpc.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/mpc_prev, ⏯️ Play/Pause:/mpc_playpause, ⏭️ Next:/mpc_next'
        - 'Reload:/mpc, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram MPC Prev"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/mpc_prev'
  action:
  - service: media_player.media_previous_track
    entity_id: media_player.mpc
  - delay: 00:00:03
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '▶️ *MPC* {{ states.media_player.mpc.state }} *{{ states.media_player.mpc.attributes.media_artist }}* - *{{ states.media_player.mpc.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/mpc_prev, ⏯️ Play/Pause:/mpc_playpause, ⏭️ Next:/mpc_next'
        - 'Reload:/mpc, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram MPC Play"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/mpc_playpause'
  action:
  - service: media_player.media_play_pause
    entity_id: media_player.mpc
  - delay: 00:00:03
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '▶️ *MPC* {{ states.media_player.mpc.state }} *{{ states.media_player.mpc.attributes.media_artist }}* - *{{ states.media_player.mpc.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/mpc_prev, ⏯️ Play/Pause:/mpc_playpause, ⏭️ Next:/mpc_next'
        - 'Reload:/mpc, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram MPC Next"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/mpc_next'
  action:
  - service: media_player.media_next_track
    entity_id: media_player.mpc
  - delay: 00:00:03
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '▶️ *MPC* {{ states.media_player.mpc.state }} *{{ states.media_player.mpc.attributes.media_artist }}* - *{{ states.media_player.mpc.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/mpc_prev, ⏯️ Play/Pause:/mpc_playpause, ⏭️ Next:/mpc_next'
        - 'Reload:/mpc, Home Menu:/start, ↩️ Back:/media'

################################################################################
