# TELEGRAM SYSTEM NOTIF ########################################################

- alias: 'Notif - Update Available'
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: persistent_notification.create
    data:
      message: "An update for Home Assistant is available."
  - service: notify.telegram
    data:
      message: "{{'\U0001F3E0'}}{{'\U00002728'}} An update for Home Assistant is available."

################################################################################

- alias: 'Notif - HASS Started'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.telegram
    data:
      message: "{{'\U0001F3E0'}}{{'\U000026A1'}} *Home Assistant* just started"

################################################################################

- alias: 'Notif - Download Failed'
  trigger:
  - platform: event
    event_type: downloader_download_failed
  action:
  - service: persistent_notification.create
    data_template:
      message: "Download failed"
  - service: notify.telegram
    data:
      message: "{{'\U0001F4E5'}}{{'\U0000274C'}} Download failed"

################################################################################

- alias: 'Notif - Disk Almost Full'
  trigger:
  - platform: numeric_state
    entity_id: sensor.disk_use_percent_home
    above: 90
    for:
      minutes: 10
  action:
  - service: persistent_notification.create
    data_template:
      message: "Disk Almost Full"
  - service: notify.telegram
    data:
      message: "{{'\U0001F4BF'}}{{'\U000026A0'}} Disk Almost Full"

# TELEGRAM DEVICE NOTIF ########################################################

- alias: 'Notif - XLNS-PC on'
  trigger:
  - platform: state
    entity_id: switch.switch_xlns_pc
    from: 'off'
    to: 'on'
  action:
  - service: notify.telegram
    data:
      message: "{{'\U0001F5A5'}}{{'\U000026A1'}} *XLNS-PC* turned on"

################################################################################

- alias: 'Notif - XLNS-PC off'
  trigger:
  - platform: state
    entity_id: switch.switch_xlns_pc
    from: 'on'
    to: 'off'
  action:
  - service: notify.telegram
    data:
      message: "{{'\U0001F5A5'}}{{'\U000026A1'}} *XLNS-PC* turned off"

################################################################################
