alias: "Telegram Remove Button"

trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    data: '/remove_button'

action:
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: '{{ trigger.event.data.message.message }}'
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
