- alias: "Telegram Service Menu"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/service'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: "{{'\U0001F4E5'}}* List of Service*"
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - "{{'\U0001F4E5'}} Downloader:/downloader, SERVICE_02:/service_02"
        - "{{'\U0001F3E0'}} Home Menu:/start"

################################################################################

- alias: "Telegram Downloader Menu"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/downloader'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: "{{'\U0001F310'}} Please enter the URL"
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - "{{'\U0001F3E0'}} Home Menu:/start"

################################################################################
