- alias: "Telegram Switch Menu"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/switch'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '⚡ *List of Switch*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - 'XLNS-PC:/xlns_pc, Portable Switch:/switch_portable, Switch_04:/switch_04'
        - 'Home Menu:/start'

################################################################################
