- alias: "Telegram Switch Portable"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/switch_portable'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '⚡ *Portable Switch* currently {{ states("switch.switch_portable") }}'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
  - service: telegram_bot.send_message
    data_template:
      message: '⚡ *Portable Switch* command'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⚡ Toggle:/switch_portable_toggle'
        - 'Home Menu:/start, ↩️ Back:/switch'

################################################################################

- alias: "Telegram Toggle Switch Portable"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/switch_portable_toggle'
  action:
  - service: homeassistant.toggle
    entity_id: switch.switch_portable
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '⚡ OK, Switching *Portable Switch*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⚡ Toggle:/switch_portable_toggle'
        - 'Home Menu:/start, ↩️ Back:/switch'

################################################################################
