- alias: "Telegram Volumio"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/volumio'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.volumio.attributes.entity_picture }}
      caption: '▶️ *Volumio* {{ states.media_player.volumio.state }} *{{ states.media_player.volumio.attributes.media_artist }}* - *{{ states.media_player.volumio.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/volumio_prev, ⏯️ Play/Pause:/volumio_playpause, ⏭️ Next:/volumio_next'
        - 'All Random:/volumio_all_random, Reload:/volumio, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Volumio Prev"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/volumio_prev'
  action:
  - service: media_player.media_previous_track
    entity_id: media_player.volumio
  - delay: 00:00:07
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.volumio.attributes.entity_picture }}
      caption: '▶️ *Volumio* {{ states.media_player.volumio.state }} *{{ states.media_player.volumio.attributes.media_artist }}* - *{{ states.media_player.volumio.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/volumio_prev, ⏯️ Play/Pause:/volumio_playpause, ⏭️ Next:/volumio_next'
        - 'All Random:/volumio_all_random, Reload:/volumio, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Volumio Play"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/volumio_playpause'
  action:
  - service: media_player.media_play_pause
    entity_id: media_player.volumio
  - delay: 00:00:07
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.volumio.attributes.entity_picture }}
      caption: '▶️ *Volumio* {{ states.media_player.volumio.state }} *{{ states.media_player.volumio.attributes.media_artist }}* - *{{ states.media_player.volumio.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/volumio_prev, ⏯️ Play/Pause:/volumio_playpause, ⏭️ Next:/volumio_next'
        - 'All Random:/volumio_all_random, Reload:/volumio, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Volumio Next"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/volumio_next'
  action:
  - service: media_player.media_next_track
    entity_id: media_player.volumio
  - delay: 00:00:07
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.volumio.attributes.entity_picture }}
      caption: '▶️ *Volumio* {{ states.media_player.volumio.state }} *{{ states.media_player.volumio.attributes.media_artist }}* - *{{ states.media_player.volumio.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/volumio_prev, ⏯️ Play/Pause:/volumio_playpause, ⏭️ Next:/volumio_next'
        - 'All Random:/volumio_all_random, Reload:/volumio, Home Menu:/start, ↩️ Back:/media'

################################################################################

- alias: "Telegram Volumio All Random"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/volumio_all_random'
  action:
  - service: media_player.shuffle_set
    entity_id: media_player.volumio
    data:
      shuffle: true
  - service: media_player.select_source
    entity_id: media_player.volumio
    data:
      source: All
  - delay: 00:00:07
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_photo
    data_template:
      url: http://192.168.1.3:8123{{ states.media_player.volumio.attributes.entity_picture }}
      caption: '▶️ *Volumio* {{ states.media_player.volumio.state }} *{{ states.media_player.volumio.attributes.media_artist }}* - *{{ states.media_player.volumio.attributes.media_title }}*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⏮️ Prev:/volumio_prev, ⏯️ Play/Pause:/volumio_playpause, ⏭️ Next:/volumio_next'
        - 'All Random:/volumio_all_random, Reload:/volumio, Home Menu:/start, ↩️ Back:/media'

################################################################################
