- platform: mqtt
  name: 'Button_A'
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: '67A622'
  payload_off: '67A622off'
  off_delay: 1

- platform: mqtt
  name: 'Button_B'
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: 'C545C0'
  payload_off: 'C545C0off'
  off_delay: 1

- platform: mqtt
  name: 'Button_C'
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: '67A621'
  payload_off: '67A621off'
  off_delay: 1

- platform: mqtt
  name: 'Button_D'
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: '67A624'
  payload_off: '67A624off'
  off_delay: 1