alias: 'Adobe Home'
initial_state: 'on'

trigger:
- platform: homeassistant
  event: start
- platform: state
  entity_id: group.family
  from: 'not_home'
  to: 'home'

condition:
- condition: state
  entity_id: group.family
  state: 'home'

action:
- service: input_select.select_option
  data:
    entity_id: input_select.current_light_theme
    option: 'Day'
- service: switch.turn_on
  entity_id: switch.switch_portable
