alias: 'Adobe Away'
initial_state: 'on'

trigger:
- platform: homeassistant
  event: start
- platform: state
  entity_id: binary_sensor.lock
  to: 'off'
  for: '00:15:00'
- platform: state
  entity_id: group.family
  to: 'not_home'
  for: '00:15:00'

condition:
- condition: state
  entity_id: group.family
  state: 'not_home'

action:
- service: input_select.select_option
  data:
    entity_id: input_select.current_light_theme
    option: 'Away'
- service: input_boolean.turn_on
  entity_id: input_boolean.text_notif
