alias: 'Current Light Theme'
initial_state: 'on'

trigger:
- platform: event
  event_type: state_changed
  event_data:
    entity_id: input_select.current_light_theme

action:
- service: scene.turn_on
  data_template:
    entity_id: "scene.{{ states.input_select.current_light_theme.state }}"
