alias: 'Current Light Theme'

trigger:
- platform: event
  event_type: state_changed
  event_data:
    entity_id: input_select.current_light_theme

condition:
- condition: state
  entity_id: input_boolean.guest_mode
  state: 'off'

action:
- service: scene.turn_on
  data_template:
    entity_id: "scene.{{ states.input_select.current_light_theme.state }}"
