homeassistant:
  # name: 'Home'
  # latitude: !secret home_latitude
  # longitude: !secret home_longitude
  # elevation: !secret home_elevation
  # unit_system: metric
  # time_zone: Asia/Jakarta
  whitelist_external_dirs:
    - '/config/'
  packages: !include_dir_named packages
  customize: !include customize.yaml
#  customize_domain:
#    automation:
#      initial_state: 'on'
  customize_glob:
    'automation.button_*':
      icon: mdi:remote
      initial_state: 'on'
    'automation.telegram_*':
      icon: mdi:telegram
      initial_state: 'on'
      hidden: true
    'automation.notif_*':
      icon: mdi:bell
      initial_state: 'on'
    'automation.hass_*':
      icon: mdi:home-assistant
      initial_state: 'on'
  media_dirs:
    media: /media
    # recording: /mnt/recordings
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret z4_ip
        - !secret xlns_pc_ip

default_config:

lovelace:
  mode: storage
  resources:
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: js
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: js
  # dashboards:
  #   lovelace-yaml:
  #     mode: yaml
  #     title: YAML
  #     icon: mdi:script
  #     show_in_sidebar: true
  #     filename: ui-lovelace.yaml

# browser_mod:
#   prefix: "browser_"
#   devices:
#     a0812e89_52cec6c4:
#       name: "Browser XLNS-PC"
#     ac02b632_280e8b9f:
#       name: "Browser Z4"

panel_iframe:
  tasmoadmin:
    title: 'TasmoAdmin'
    icon: mdi:lightbulb-on
    url: http://192.168.1.3:9541
  ide:
    title: 'IDE'
    icon: mdi:code-braces
    url: http://192.168.1.3:8321

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

ifttt:
  key: !secret ifttt_key

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids: !include telegram_chat_id.yaml

notify:
  - name: 'Pushbullet'
    platform: pushbullet
    api_key: !secret pushbullet_api
  - name: 'Telegram'
    platform: telegram
    chat_id: !secret xlns_telegram_id

discovery:
  # ignore:
  #   - igd

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret aqara_key
      mac: !secret aqara_mac
      host: 192.168.1.24

# yeelight:
#   devices:
#     192.168.1.22:
#       name: 'Main Light'
#       model: color1
#   custom_effects:
#     - name: 'Fire Flicker'
#       flow_params:
#         count: 0
#         transitions:
#           - TemperatureTransition: [1900, 1000, 80]
#           - TemperatureTransition: [1900, 2000, 60]
#           - SleepTransition:       [1000]

#camera:
#  - platform: generic
#    name: 'Volumio Album Art'
#    still_image_url: http://192.168.1.3:8123{{ states.media_player.volumio.attributes.entity_picture }}

device_tracker:
  - platform: google_maps
    max_gps_accuracy: 100
    username: !secret google_maps_username
    consider_home: 300
#  - platform: bluetooth_tracker
#    consider_home: 300

google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret

weather:
  - platform: darksky
    api_key: !secret darksky_api

downloader:
  download_dir: download

http:
#  api_password: !secret http_api_password
#  base_url: !secret http_base_url
#  server_port: !secret http_port
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5

logger:
  default: info
  logs:
    homeassistant.components.media_player.mpchc: fatal

tts:
  - platform: google_translate
    service_name: google_say

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

map:
sun:
cloud:
config:
person:
updater:
wake_on_lan:
conversation:
system_health:

zone: #!include zone.yaml
logbook: !include logbook.yaml
history: !include history.yaml
recorder: !include recorder.yaml

scene: !include_dir_list scene
sensor: !include_dir_list sensor
switch: !include_dir_list switch
automation: !include_dir_list automation
media_player: !include_dir_list media_player
binary_sensor: !include_dir_list binary_sensor

group: !include_dir_named group
script: !include_dir_named script
input_select: !include_dir_named input_select
input_boolean: !include_dir_named input_boolean
input_datetime: !include_dir_named input_datetime