- platform: mqtt
  state_topic: "tele/RF_Bridge/RESULT"
  name: 'Sensor'
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: 'D54C1E'
  payload_off: 'D54C1Eoff'
  device_class: motion
  qos: 1