#----------------------------------------------------------------------------------------------------#
# custom header
#----------------------------------------------------------------------------------------------------#
custom_header: {}
#----------------------------------------------------------------------------------------------------#
# resources
#----------------------------------------------------------------------------------------------------#
resources:
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js
  - url: /community_plugin/upcoming-media-card/upcoming-media-card.js
    type: js
#----------------------------------------------------------------------------------------------------#
# UI
#----------------------------------------------------------------------------------------------------#
title: XLNS Home

######################################################################################################
# Home
######################################################################################################
views:
  - title: HOME
    icon: ''
    panel: false
    path: home
    cards:
#----------------------------------------------------------------------------------------------------#
      - type: vertical-stack
        cards:
#----------------------------------------------------------------------------------------------------#
        - type: markdown
          card_size: 4
          content: |
                <font size='24'><b>{{ states('sensor.time') }}</b></font><br>
                <b>{{ states('sensor.day') }}, {{ states('sensor.date_text') }}</b> <br> 
                
                {% set t = now().hour %}
                {% if t <= 1 %} <b>Met tidur</b> {{'\U0001F611'}}
                {% elif t <= 3 %} <b>Met tidur</b> {{'\U0001F62A'}}
                {% elif t <= 5 %} <b>Met tidur</b> {{'\U0001F634'}}
                {% elif t <= 7 %} <b>Met pagi</b> {{'\U0001F4A9'}}
                {% elif t <= 9 %} <b>Met pagi</b> {{'\u2615\uFE0F'}}
                {% elif t <= 10.5 %} <b>Met pagi</b> {{'\U0001F642'}}
                {% elif t <= 13 %} <b>Met siang</b> {{'\U0001F60A'}}
                {% elif t <= 15 %} <b>Met siang</b> {{'\U0001F60E'}}
                {% elif t <= 17 %} <b>Met siang</b> {{'\U0001F44B\U0001F3FB'}}
                {% elif t <= 19 %} <b>Met malem</b> {{'\U0001F44B\U0001F3FB'}}
                {% elif t <= 22 %} <b>Met malem</b> {{'\U0001F60C'}}
                {% elif t <= 23 %} <b>Met malem</b> {{'\U0001F974'}}
                {% else %} <b>Met malem</b> {{'\U0001F974'}}
                {% endif %}
#----------------------------------------------------------------------------------------------------#
        - type: horizontal-stack
          cards:
#----------------------------------------------------------------------------------------------------#
          - type: picture-entity
            entity: person.joko
            aspect_ratio: 100%
            state_image:
              home: /local/joko.png
              not_home: /local/joko_gray.png
#----------------------------------------------------------------------------------------------------#
          - type: picture-entity
            entity: device_tracker.google_maps_117945900463931421410
            aspect_ratio: 100%
            state_image:
              home: /local/blank.png
              not_home: /local/blank.png
#----------------------------------------------------------------------------------------------------#
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.joko_to_home
            - entity: device_tracker.google_maps_101676721020210595319
              secondary_info: last-changed
            - entity: device_tracker.z4
              secondary_info: last-changed
            - entity: sensor.steam_76561198066698938
              secondary_info: last-changed
#----------------------------------------------------------------------------------------------------#
      - type: vertical-stack
        cards:
#----------------------------------------------------------------------------------------------------#
        - type: weather-forecast
          entity: weather.dark_sky
#----------------------------------------------------------------------------------------------------#
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sun.sun
            - entity: sensor.dark_sky_summary
#----------------------------------------------------------------------------------------------------#
      - type: entity-filter
        entities:
          - media_player.kodi
          - media_player.plex_chrome
          - media_player.volumio
          - media_player.mpc
          - media_player.vlc
        state_filter:
          - 'on'
          - idle
          - paused
          - playing
#----------------------------------------------------------------------------------------------------#
      - type: entities
        title: Home Mode
        show_header_toggle: false
        entities:
          - entity: input_select.current_light_theme
          - entity: input_select.adobe_status
        footer:
          type: buttons
          entities:
            - automation.gaming_mode
            - input_boolean.guest_mode
            - input_boolean.speech_notif
            - input_boolean.text_notif
#----------------------------------------------------------------------------------------------------#
        # - type: glance
        #   show_name: false
        #   show_state: false
        #   entities:
        #     - automation.gaming_mode
        #     - input_boolean.guest_mode
        #     - input_boolean.speech_notif
        #     - input_boolean.text_notif
#----------------------------------------------------------------------------------------------------#
      - type: entities
        title: Switch
        show_header_toggle: false
        entities:
          - entity: switch.xlns_pc
          - entity: switch.switch_portable
          - entity: switch.speaker
#----------------------------------------------------------------------------------------------------#
      - type: entities
        title: Light
        show_header_toggle: false
        entities:
          - entity: light.mi_gateway
          - entity: light.main_light
#----------------------------------------------------------------------------------------------------#
      # - type: entities
      #   title: Routine Trigger
      #   show_header_toggle: false
      #   entities:
      #     - entity: input_boolean.good_morning
      #     - entity: input_boolean.good_night
      #     - entity: group.button
######################################################################################################
# FAMILY
######################################################################################################
  - title: FAMILY
    icon: ''
    panel: false
    path: family
    cards:
#----------------------------------------------------------------------------------------------------#
      - type: map
        default_zoom: 14
        entities:
          - entity: device_tracker.google_maps_101676721020210595319
          - entity: zone.work
          - entity: zone.home
#----------------------------------------------------------------------------------------------------#
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
#----------------------------------------------------------------------------------------------------#
          - type: picture-entity
            entity: person.joko
            aspect_ratio: 100%
            state_image:
              home: /local/joko.png
              not_home: /local/joko_gray.png
#----------------------------------------------------------------------------------------------------#
          - type: picture-entity
            entity: device_tracker.google_maps_117945900463931421410
            aspect_ratio: 100%
            state_image:
              home: /local/blank.png
              not_home: /local/blank.png
#----------------------------------------------------------------------------------------------------#
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.joko_to_home
            - entity: device_tracker.google_maps_101676721020210595319
              secondary_info: last-changed
            - entity: device_tracker.z4
              secondary_info: last-changed
            - entity: sensor.steam_76561198066698938
              secondary_info: last-changed
######################################################################################################
# MEDIA
######################################################################################################
  - title: MEDIA
    icon: ''
    panel: false
    path: media
    cards:
#----------------------------------------------------------------------------------------------------#
      - type: entity-filter
        entities:
          - media_player.kodi
          - media_player.plex_chrome
          - media_player.volumio
          - media_player.mpc
          - media_player.vlc
        state_filter:
          - 'on'
          - idle
          - paused
          - playing
#----------------------------------------------------------------------------------------------------#
      - type: 'custom:upcoming-media-card'
        entity: sensor.recently_added
        title: Recently Added
        clock: 24
        date: ddmm
        text_shadows: false
        accent_color: var(--app-header-background-color)
        box_shadows: false
#----------------------------------------------------------------------------------------------------#
      - type: media-control
        entity: media_player.mpc
#----------------------------------------------------------------------------------------------------#
      - type: media-control
        entity: media_player.volumio
#----------------------------------------------------------------------------------------------------#
      - type: media-control
        entity: media_player.kodi
#----------------------------------------------------------------------------------------------------#
      - type: media-control
        entity: media_player.plex_chrome
#----------------------------------------------------------------------------------------------------#
      - type: media-control
        entity: media_player.vlc
#----------------------------------------------------------------------------------------------------#
      - type: entities
        entities:
          - entity: sensor.radarr_movies
          - entity: sensor.radarr_upcoming
          - entity: sensor.sonarr_series
          - entity: sensor.sonarr_upcoming
          - entity: sensor.sonarr_wanted
          - entity: sensor.sonarr_disk_space
#----------------------------------------------------------------------------------------------------#
      - type: entities
        entities:
#----------------------------------------------------------------------------------------------------#
          - type: weblink
            icon: 'mdi:play-circle'
            name: Volumio
            url: 'http://192.168.1.5/'
#----------------------------------------------------------------------------------------------------#
          - type: weblink
            icon: 'mdi:library-video'
            name: Plex
            url: 'http://192.168.1.2:32400/web'
#----------------------------------------------------------------------------------------------------#
          - type: weblink
            icon: 'mdi:library-video'
            name: AIMP
            url: 'http://192.168.1.2:3333/index.htm'
######################################################################################################
# AIMP
######################################################################################################
  - title: AIMP
    icon: ''
    panel: true
    path: aimp
    cards:
      - aspect_ratio: 48%
        type: iframe
        url: 'http://192.168.1.2:3333/index.htm'
######################################################################################################
# AUTOMATION
######################################################################################################
  - title: AUTOMATION
    icon: ''
    panel: false
    path: automation
    cards:
#----------------------------------------------------------------------------------------------------#
      - type: entities
        show_header_toggle: false
        entities:
          - entity: group.automation
          - entity: group.automation_telegram
#----------------------------------------------------------------------------------------------------#
      - type: vertical-stack
        cards:
#----------------------------------------------------------------------------------------------------#
          - type: entities
            title: Automation
            show_header_toggle: false
            entities:
              - entity: automation.routine_good_morning
              - entity: automation.alarm
              - entity: input_datetime.good_morning
#----------------------------------------------------------------------------------------------------#
          - type: horizontal-stack
            cards:
#----------------------------------------------------------------------------------------------------#
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: automation.switch_timer
                  - entity: input_datetime.switch_timer
                  - entity: input_select.switch_timer
#----------------------------------------------------------------------------------------------------#
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: automation.switch_timer_2
                  - entity: input_datetime.switch_timer_2
                  - entity: input_select.switch_timer_2
#----------------------------------------------------------------------------------------------------#
      - type: vertical-stack
        cards:
#----------------------------------------------------------------------------------------------------#
        - type: entities
          title: Home Mode
          show_header_toggle: false
          entities:
            - entity: input_select.current_light_theme
            - entity: input_select.adobe_status
          # footer:
          #   type: buttons
          #   entities:
          #     - automation.gaming_mode
          #     - input_boolean.guest_mode
          #     - input_boolean.speech_notif
          #     - input_boolean.text_notif
#----------------------------------------------------------------------------------------------------#
        - type: entities
          show_header_toggle: false
          entities:
            - entity: input_boolean.guest_mode
            - entity: automation.gaming_mode
            - entity: input_boolean.speech_notif
            - entity: input_boolean.text_notif
#----------------------------------------------------------------------------------------------------#
      - entities:
          - entity: input_boolean.good_morning
          - entity: input_boolean.good_night
        show_header_toggle: false
        title: Routine Trigger
        type: entities
######################################################################################################
# SYSTEM
######################################################################################################
  - title: SYSTEM
    icon: ''
    panel: false
    path: system
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - entity: input_select.current_ui_theme
          - entity: automation.hass_auto_backup
          - entity: automation.hass_auto_restart
#----------------------------------------------------------------------------------------------------#
      - type: entities
        entities:
          - entity: switch.adguard_filtering
          - entity: switch.adguard_parental_control
          - entity: sensor.adguard_dns_queries
          - entity: sensor.adguard_dns_queries_blocked_ratio
          - entity: sensor.adguard_parental_control_blocked
#----------------------------------------------------------------------------------------------------#
      - type: vertical-stack
        cards:
#----------------------------------------------------------------------------------------------------#
          - type: horizontal-stack
            cards: 
#----------------------------------------------------------------------------------------------------#
              - type: gauge
                entity: sensor.processor_use
                name: 'CPU'
                severity:
                  green: 0
                  yellow: 45
                  red: 85
#----------------------------------------------------------------------------------------------------#
              - type: gauge
                entity: sensor.memory_use_percent
                name": 'Memory'
                severity:
                  green: 0
                  yellow: 45
                  red: 85
#----------------------------------------------------------------------------------------------------#
              - type: gauge
                entity: sensor.disk_use_percent_home
                name: 'Disk'
                severity:
                  green: 0
                  yellow: 45
                  red: 85
#----------------------------------------------------------------------------------------------------#
          - type: entities
            title: Home Assistant
            show_header_toggle: false
            entities:
              - entity: sensor.installed_version
              - entity: sensor.latest_version_text
              - entity: sensor.home_assistant_v2_db
              - entity: sensor.memory_free
              - entity: sensor.disk_free_home
              - entity: sensor.ipv4_address_eth0
              - entity: sensor.uptime
#----------------------------------------------------------------------------------------------------#
          - type: entities
            show_header_toggle: false
            entities:
              - entity: script.hass_restart
#----------------------------------------------------------------------------------------------------#
      - type: entities
        title: Link
        show_header_toggle: false
        entities:
#----------------------------------------------------------------------------------------------------#
          - icon: 'mdi:access-point'
            name: Modem
            type: weblink
            url: 'http://192.168.8.1/'
#----------------------------------------------------------------------------------------------------#
          - icon: 'mdi:router-wireless'
            name: Router
            type: weblink
            url: 'http://192.168.1.1/'
#----------------------------------------------------------------------------------------------------#
          - icon: 'mdi:format-list-bulleted'
            name: State UI
            type: weblink
            url: 'http://192.168.1.3:8123/states'
#----------------------------------------------------------------------------------------------------#
