alias: "Telegram Restart Hass"

trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/restart'

action:
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: "{{'\U000026A1'}} OK, restarting *Home Assistant*"
    target: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: "{{'\U00002699'}} *System Command*"
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
    inline_keyboard:
      - "{{'\U00002699'}} System Status:/system_status, {{'\U000026A1'}} Restart:/restart"
      - "{{'\U0001F3E0'}} Home Menu:/start"
- service: homeassistant.restart