alias: 'Yeelight Auto-On'
initial_state: 'on'

trigger:
- platform: state
  entity_id: binary_sensor.motion
  to: 'on'

condition:
- condition: state
  entity_id: light.yeelight
  state: 'off'
- condition: time
  after: '17:30:00'
  before: '05:00:00'

action:
- service: light.turn_on
  entity_id: light.yeelight