alias: "Telegram MPC Play"

trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    data: '/mpc_playpause'

action:
- service: media_player.media_play_pause
  entity_id: media_player.mpc
- delay: 00:00:03
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: "{{'\U000025B6'}} *MPC* {{ states.media_player.mpc.state }} *{{ states.media_player.mpc.attributes.media_artist }}* - *{{ states.media_player.mpc.attributes.media_title }}*"
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
    inline_keyboard:
      - "{{'\U000023EE'}} Prev:/mpc_prev, {{'\U000023EF'}} Play/Pause:/mpc_playpause, {{'\U000023ED'}} Next:/mpc_next"
      - "{{'\U0001F504'}} Reload:/mpc, {{'\U0001F3E0'}} Home Menu:/start, {{'\U000021A9'}} Back:/media"