alias: "Telegram Kodi"

trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    data: '/kodi'

action:
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_photo
  data_template:
    url: http://192.168.1.3:8123{{ states.media_player.kodi.attributes.entity_picture }}
    caption: "{{'\U000025B6'}} *Kodi* {{ states.media_player.kodi.state }} *{{ states.media_player.kodi.attributes.media_artist }}* - *{{ states.media_player.kodi.attributes.media_title }}*"
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
    inline_keyboard:
      - "{{'\U000023EE'}} Prev:/kodi_prev, {{'\U000023EF'}} Play/Pause:/kodi_playpause, {{'\U000023ED'}} Next:/kodi_next"
      - "{{'\U0001F504'}} Reload:/kodi, {{'\U0001F3E0'}} Home Menu:/start, {{'\U000021A9'}} Back:/media"
