alias: "Telegram Family Menu"

trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    data: '/family'

action:
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: "{{'\U0001F464'}} *List of Family*"
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
    inline_keyboard:
      - "Joko:/joko"
      - "{{'\U0001F3E0'}} Home Menu:/start"