alias: 'Button A'

trigger:
- platform: template
  value_template: "{{ is_state('sensor.rf_command', 'A') }}"

action:
- service: input_select.select_option
  data:
    entity_id: input_select.adobe_status
    option: 'Away'
- service: input_select.select_option
  data:
    entity_id: input_select.current_light_theme
    option: 'Away'
- service: input_boolean.turn_on
  entity_id: input_boolean.text_notif
