alias: 'Button B'

trigger:
- platform: template
  value_template: "{{ is_state('sensor.rf_command', 'B') }}"

action:
- service: input_select.select_option
  data:
    entity_id: input_select.adobe_status
    option: 'Home'
- service: input_select.select_option
  data:
    entity_id: input_select.current_light_theme
    option: 'Day'
- service: switch.turn_on
  entity_id: switch.switch_portable
