alias: "Telegram Chrome Prev"

trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    data: '/chrome_prev'

action:
- service: media_player.media_previous_track
  entity_id: media_player.chrome
- delay: 00:00:07
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: "{{'\U000025B6'}} *Chrome* {{ states.media_player.chrome.state }} *{{ states.media_player.chrome.attributes.media_artist }}* - *{{ states.media_player.chrome.attributes.media_title }}*"
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
    inline_keyboard:
      - "{{'\U000023EE'}} Prev:/chrome_prev, {{'\U000023EF'}} Play/Pause:/chrome_playpause, {{'\U000023ED'}} Next:/chrome_next"
      - "{{'\U0001F504'}} Reload:/chrome, {{'\U0001F3E0'}} Home Menu:/start, {{'\U000021A9'}} Back:/media"