alias: 'Button A'

trigger:
- platform: state
  entity_id: binary_sensor.button_a
  to: 'on'

action:
- service: input_select.select_option
  data:
    entity_id: input_select.adobe_status
    option: 'Away'
- service: input_select.select_option
  data:
    entity_id: input_select.current_light_theme
    option: 'Away'
- service: input_boolean.turn_on
  entity_id: input_boolean.text_notif
