alias: 'Button B'

trigger:
- platform: state
  entity_id: binary_sensor.button_b
  to: 'on'

action:
- service: input_select.select_option
  data:
    entity_id: input_select.adobe_status
    option: 'Home'
- service: input_select.select_option
  data:
    entity_id: input_select.current_light_theme
    option: 'Day'
- service: switch.turn_on
  entity_id: switch.switch_portable
