alias: 'Button D'

trigger:
- platform: state
  entity_id: binary_sensor.button_d
  to: 'on'

action:
- service: input_select.select_option
  data:
    entity_id: input_select.current_light_theme
    option: "Sleep"
- service: switch.turn_on
  entity_id: switch.switch_portable
- service: input_boolean.turn_off
  data:
    entity_id: input_boolean.good_night