alias: 'Notif - Update Available'

trigger:
- platform: state
  entity_id: binary_sensor.updater
  to: 'on'

action:
- service: persistent_notification.create
  data_template:
    notification_id: 01
    title: 'Update available'
    message: '
    [Update](http://192.168.1.3:8123/hassio/dashboard) Home Assistant available: {{ states.sensor.latest_version.state }}
    
    Currently running version {{ states.sensor.installed_version.state }}'
