alias: "Telegram Switch_04 Toggle"

trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    data: '/switch_04_toggle'

action:
- service: homeassistant.toggle
  entity_id: switch.switch_04
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: "{{'\U000026A1'}} OK, Switching *Switch-04*"
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
    inline_keyboard:
      - "{{'\U000026A1'}} Toggle:/switch_04_toggle"
      - "{{'\U0001F3E0'}} Home Menu:/start, {{'\U000021A9'}} Back:/switch"