alias: 'Notif - Update Available'

trigger:
- platform: state
  entity_id: updater.updater

action:
- service: persistent_notification.create
  data:
    message: "An update for Home Assistant is available."
- service: notify.telegram
  data:
    message: "{{'\U0001F3E0'}}{{'\U00002728'}} An update for Home Assistant is available."