alias: "Telegram Light Main"

trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    data: '/light_main'

action:
- service: telegram_bot.delete_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
- service: telegram_bot.send_message
  data_template:
    message: "*Main Light* currently {{ states('light.yeelight') }}

{{'\U0001F4A1'}} *Main Light Command*"
    target: '{{ trigger.event.data.user_id }}'
    disable_notification: true
    inline_keyboard:
      - "{{'\U000026A1'}} Toggle:/light_main_toggle"
      - "{{'\U0001F3E0'}} Home Menu:/start, {{'\U000021A9'}} Back:/light"
