alias: 'Notif - XLNS-PC on'

trigger:
- platform: state
  entity_id: switch.switch_xlns_pc
  from: 'off'
  to: 'on'

action:
- service: notify.telegram
  data:
    message: "{{'\U0001F5A5'}}{{'\U000026A1'}} *XLNS-PC* turned on"