# HASS #########################################################################

- id: hass_autorestart
  alias: "Hass - Auto Restart"
  trigger:
  - platform: time
    at: '01:30:00'
  condition:
  - condition: time
    weekday:
      - mon
      - wed
      - sat
  action:
  - service: homeassistant.restart

################################################################################

- id: hass_autobackup
  alias: "Hass - Auto Backup"
  trigger:
  - platform: time
    at: '01:30:00'
  condition:
  - condition: time
    weekday:
      - sun
  action:
  - service: hassio.snapshot_full

# SWITCH  ######################################################################

- alias: "Portable Switch timer"
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state  == (states.input_datetime.portable_switch_timer.attributes.timestamp | int | timestamp_custom("%H:%M", False))  }}'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.switch_portable

# PRESENCE #####################################################################

- alias: "Coming Home"
  trigger:
  - platform: state
    entity_id: device_tracker.xperia_z3
    to: 'home'
  condition:
  - condition: state
    entity_id: switch.switch_portable
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.switch_portable

################################################################################

- id: sunrise
  alias: "Sunrise"
  trigger:
  - platform: time
    at: '06:30:00'
  condition:
  - condition: state
    entity_id: group.family
    state: 'home'
  action:

################################################################################