- alias: 'Away Mode'
  trigger:
  - platform: state
    entity_id: group.family
    to: 'not_home'
    for: '00:11:00'
  - platform: state
    entity_id: input_boolean.good_night
    to: 'on'

  condition:
  - condition: state
    entity_id: group.family
    state: 'not_home'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'

  action:
  - service: light.turn_off
    entity_id: light.main_light
  - service: input_boolean.turn_off
    entity_id: input_boolean.good_night