- alias: 'Away Mode'
  trigger:
  - platform: state
    entity_id: group.family
    to: 'not_home'
    for: '00:05:00'
  - platform: state
    entity_id: input_boolean.good_night
    to: 'on'
  - platform: state
    entity_id: device_tracker.xperia_z3
    from: 'away'
    to: 'home'
    for: '00:00:11'
  - platform: state
    entity_id: binary_sensor.button_a
    to: 'on'
  
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'

  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.current_light_theme
      option: "Away"
  - service: input_boolean.turn_on
    entity_id: input_boolean.text_notifications
  - service: input_boolean.turn_on
    entity_id: input_boolean.away_mode
  - service: input_boolean.turn_on
    entity_id: input_boolean.alert_mode