- alias: 'Gaming Mode'
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.steam_76561198066698938

  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: or
    conditions:
    - condition: template
      value_template: "{{is_state_attr('sensor.steam_76561198066698938', 'game', 'Dota 2')}}"
    - condition: template
      value_template: "{{is_state_attr('sensor.steam_76561198066698938', 'game', 'Arfifact')}}"

  action:
  - service: light.turn_on
    data:
      entity_id: light.main_light
      brightness: 3
      color_temp: 588
      transition: 30
  - service: scene.turn_on
    entity_id: scene.movies
