alias: 'Gaming Mode'
trigger:
- platform: event
  event_type: state_changed
  event_data:
    entity_id: sensor.steam_76561198066698938

condition:
- condition: state
  entity_id: input_boolean.guest_mode
  state: 'off'
- condition: or
  conditions:
  - condition: template
    value_template: "{{is_state_attr('sensor.steam_76561198066698938', 'game', 'Dota 2')}}"
  - condition: template
    value_template: "{{is_state_attr('sensor.steam_76561198066698938', 'game', 'Arfifact')}}"

action:
- service: input_select.select_option
  data:
    entity_id: input_select.current_light_theme
    option: "Movies"
