- alias: 'Good Night Trigger'
  trigger:
  - platform: state
    entity_id: input_boolean.good_night
    to: 'on'
    from: 'off'

  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'

  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.current_light_theme
      option: "Sleep"
  - service: switch.turn_on
    entity_id: switch.switch_portable
  - service: input_boolean.turn_off
    entity_id: input_boolean.good_night