- alias: 'Good Morning Routine'
  trigger:
  - platform: state
    entity_id: input_boolean.good_morning
    to: 'on'
    from: 'off'
  - platform: template
    value_template: '{{ states.sensor.time.state  == (states.input_datetime.good_morning_time.attributes.timestamp | int | timestamp_custom("%H:%M", False))  }}'
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat

  action:
  - service: light.turn_on
    data:
      entity_id: light.main_light
      brightness: 255
      color_temp: 153
      transition: 30
  - service: homeassistant.turn_off
    entity_id: switch.switch_portable
  - service: input_boolean.turn_off
    entity_id: input_boolean.good_morning
