- alias: "Telegram System Menu"
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/system'
  action:
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '*⚙️ System Command*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⚙️ System Status:/system_status, ⚡ Restart:/restart'
        - 'Home Menu:/start'

################################################################################

- alias: "Telegram System Status"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/system_status'
  action:
  - service: telegram_bot.send_message
    data_template:
      message: '⚙️ *HASS* uptime {{ states("sensor.uptime") }} day
      
      Disk {{ states("sensor.disk_use_percent_home") }} % used'
      target: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '*⚙️ System Command*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⚙️ System Status:/system_status, ⚡ Restart:/restart, Backup Config:/snapshot'
        - 'Home Menu:/start'

################################################################################

- alias: "Telegram Restart Hass"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/restart'
  action:
  - service: homeassistant.restart
  - service: telegram_bot.delete_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '⚡ OK, restarting *Home Assistant*'
      target: '{{ trigger.event.data.user_id }}'
  - service: telegram_bot.send_message
    data_template:
      message: '*⚙️ System Command*'
      target: '{{ trigger.event.data.user_id }}'
      disable_notification: true
      inline_keyboard:
        - '⚙️ System Status:/system_status, ⚡ Restart:/restart'
        - 'Home Menu:/start'

################################################################################

