esphome:
  name: speaker
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Speaker Fallback"
    password: !secret wifi_password

captive_portal:

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Speaker Button GPIO0"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    internal: true
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Speaker Button GPIO14"
    on_state:
      - switch.toggle: relay

switch:
  - platform: gpio
    icon: mdi:speaker
    name: "Speaker"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes