alias: 'Hass - Auto Backup'

trigger:
- platform: time
  at: '01:30:00'

condition:
- condition: time
  weekday:
  - sun

action:
- service: hassio.snapshot_full
  data_template:
    name: Automated Backup {{ now().strftime('%Y-%m-%d') }}