alias: 'Hass - Feedback'

trigger:
- platform: template
  value_template: >
    {% if states('sensor.rf_command') == 'A' %}
      True
    {% elif states('sensor.rf_command') == 'B' %}
      True
    {% elif states('sensor.rf_command') == 'C' %}
      True
    {% elif states('sensor.rf_command') == 'D' %}
      True
    {% endif %}
action:
- service: xiaomi_aqara.play_ringtone
  data:
    gw_mac: !secret aqara_mac
    ringtone_id: 10007
    ringtone_vol: 50
- service: light.turn_on
  data:
    entity_id: light.mi_gateway
    brightness: 91
    rgb_color: [255,36,36]
- delay: 00:00:00.5
- service: light.turn_off
  data:
    entity_id: light.mi_gateway