alias: 'Notif - Update Available'

trigger:
- platform: state
  entity_id: binary_sensor.updater

action:
- service: persistent_notification.create
  data:
    notification_id: 01
    title: 'Update available'
    message: 'An [update](http://192.168.1.3:8123/hassio/dashboard) for Home Assistant is available.'
